In [17]:
%matplotlib inline

import numpy as np
from sklearn.linear_model import LinearRegression

import pandas as pd
import matplotlib.pyplot as plt

# Make the graphs a bit prettier, and bigger
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (15, 5)

In [26]:
df_all_nominated = pd.read_csv('./data/oscar_all_nominations.csv', skipinitialspace=True)
df_all_winners = pd.read_csv('./data/oscar_age.csv', skipinitialspace=True)

In [10]:
df_all_nominated

,year,category,winner,entity
0,1927,ACTOR,False,Richard Barthelmess
1,1927,ACTOR,True,Emil Jannings
2,1927,ACTRESS,False,Louise Dresser
3,1927,ACTRESS,True,Janet Gaynor
4,1927,ACTRESS,False,Gloria Swanson
...,...,...,...,...
11053,2017,SCIENTIFIC AND TECHNICAL AWARD (Scientific and...,True,"To LEONARD CHAPMAN for the overall concept, de..."
11054,2017,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,True,To JASON SMITH and JEFF WHITE for the original...
11055,2017,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,True,"To JOE MANCEWICZ, MATT DERKSEN and HANS RIJPKE..."
11056,2017,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,True,To ALEX POWELL for his contribution to the des...
11057,2017,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,True,To ROB JENSEN for the foundational design and ...

In [20]:
df_all_winners

,year,age,name,movie,gender
0,1927,22,Janet Gaynor,"Seventh Heaven, Street Angel and Sunrise: A So...",f
1,1927,44,Emil Jannings,"Seventh Heaven, Street Angel and Sunrise: A So...",m
2,1928,41,Warner Baxter,Coquette,m
3,1928,37,Mary Pickford,Coquette,f
4,1929,62,George Arliss,The Divorcee,m
...,...,...,...,...,...
187,2020,63,Frances McDormand,Nomadland,f
188,2021,53,Will Smith,The Eyes of Tammy Faye,m
189,2021,44,Jessica Chastain,The Eyes of Tammy Faye,f
190,2022,60,Michelle Yeoh,Everything Everywhere All at Once,f
191,2022,54,Brendan Fraser,Everything Everywhere All at Once,m

In [36]:

merged_data = pd.merge(df_all_nominated, df_all_winners, left_on=['entity', 'category'], right_on=['name', 'category'], how='left')

# Enregistrer le rÃ©sultat fusionnÃ© dans un nouveau fichier CSV
merged_data.to_csv('merged_data.csv', index=False)

KeyError: 'category'